site_name: AppAmbit
theme:
  name: material
  custom_dir: docs/custom_theme
  logo: images/logo.png
  favicon: images/logo.png
  text: "Go to Website"
  palette:
    scheme: slate  # This provides a dark background
    primary: custom  # We'll define this custom color in extra.css
    accent: orange
    
   
features:
  - content.code.copy
  - content.code.annotate
  - navigation.tabs
  - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.10/clipboard.min.js
  
nav:
  - Introduction: index.md
  - Rest:
      - Api: Rest/api.md
  - NetMAUI:
      - Getting Start: NetMAUI/getting.md
      - Crash Detection: NetMAUI/crashDetection.md
      - Logging: NetMAUI/logging.md
      - Analytics: NetMAUI/Analytics.md
  - Flutter (Coming Soon): features/web-app.md
  - React Native (Coming Soon): features/web-app.md