site_name: ""  # This removes the site name from the header
theme:
  name: material
  custom_dir: docs/custom_theme
  logo: images/logo-bright.svg
  favicon: images/logo.png
  palette:
    scheme: slate  # Dark background
    primary: custom  # Custom color defined in extra.css
    accent: orange

features:
  - content.code.copy
  - content.code.annotate
  - navigation.tabs
  - navigation.sections

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.10/clipboard.min.js
  
nav:
  - Introduction: index.md
  - Rest:
      - Authenticating requests: Authentication/auth.md
      - Endpoints:
          Register: Rest/consumer.md
          Logging: Rest/post_log.md
          Sart Session: Rest/post_session_start.md
          End Session: Rest/post_session_end.md
          Analytics: Rest/Analytics.md
  - NetMAUI:
      - Getting Started: NetMAUI/getting.md
      - Crash Detection: NetMAUI/crashDetection.md
      - Logging: NetMAUI/logging.md
      - Analytics: NetMAUI/Analytics_MAUI.md
  - Flutter (Coming Soon): features/web-app.md
  - React Native (Coming Soon): features/web-app.md
