site_name: AppAmbit
theme:
  name: material
palette:
    scheme: slate  # Enables dark mode
    primary: deep purple
    accent: amber
   
features:
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.sections

extra_css:
  - Stylesheets/extra.css

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.10/clipboard.min.js

nav:
  - Introduction: index.md
  - Rest:
      - Api: Rest/api.md
  - NetMAUI:
      - Getting Start: NetMAUI/getting.md
      - Crash Detection: NetMAUI/crashDetection.md
      - Logging: NetMAUI/logging.md
      - Analytics: NetMAUI/Analytics.md
  - Flutter (CommingSoon): features/web-app.md
  - React Native (Comming Soon): features/web-app.md
      
